### ISSUE TITLE
Handle licenses for style objects

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Django#142]
Currently there is no license handling or metadata for style resources. We should either:

1. Offer an option for users to select a license when uploading styles, and offer only a choice of licenses we deem as suitable. Then we need to show this license explicitly on the style resource page so that users know if they are able to use the style without issue.

or 

2. Select a single license and make it clear that any resources added are under this license. We'd have to go with something super-permissive such as cc-0. 

Potentially 1 is a better approach, as it's possible to eg create a symbol which uses a svg drawing created by someone else who has published it under a different license than we force with approach 2 (ie using svg created under a CC-NC license or CC-SA license will force the symbol to be published under a similar license) . We'd just have to make the license selection option when uploading styles strongly suggest that the submitter DOESN'T pick a "CC-BY" type license, as the last thing we want is to require users to have a ridiculously long attribution string on their maps ("red star marker by Some Person, blue polygon fill by Another Person, Lake Legend Shape by Yet Another Person")

**Comment by nyalldawson** [comment]
(This should really be treated as high priority -- without a clear license the style repository is not professional/enterprise friendly!)

**Comment by timlinux** [comment]
Hi @nyalldawson 

Yeah I was thinking about this too. Personally I was going to go with option 2 in your list. I have a few reasons for this:

* Requiring publishers to understand different license regiemes is not very friendly, easier to have a blanket rule
* I don't want us to have to act as 'license police', we dont have the resources for it, it is better to put the onus on the user to ensure everything is freely sharable. @sumandari we should have a note on all the upload page saying 'I confirm that I own these materials and have the rights to share them, including any embedded content, under the CC-0 license.
* Requiring attribution on maps or shared projects is going to be a pain and I don't want to make the user have to keep track off all the attribution requirements of all the styles they have (as you mention in cases where the is CC-BY)
* Once a style has been added to QGIS, it is hard to even know what the license of the style without going back to the original share. We could come up with a tagging system or something but I think it is going to require a level of organisation that most users won't have and they will inevitably end up breaching the licenses.

BTW I am planning to add additional resource types for composer templates, small demonstrator projects (all in a GPKG), colour pallettes, etc. and would like to use the same regieme everywhere : Upload here and be aware that your work will be freely shared, modified and used with no attribution (i.e. CC-0). The GPKG sharing may be an exception to this where I was going to require that any layer data has it's metadata properties populated so that we can make sure e.g. OSM data has been attributed.

@sumandari On the web site for each resource page we should provide a message indicating the license with a link to https://creativecommons.org/publicdomain/zero/1.0/. Also when a user downloads a resource, it would be good if they get it in a zip file which includes the license in Text form:

----------------

     CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES NOT PROVIDE LEGAL SERVICES. DISTRIBUTION OF THIS DOCUMENT DOES NOT CREATE AN ATTORNEY-CLIENT RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS INFORMATION ON AN "AS-IS" BASIS. CREATIVE COMMONS MAKES NO WARRANTIES REGARDING THE USE OF THIS DOCUMENT OR THE INFORMATION OR WORKS PROVIDED HEREUNDER, AND DISCLAIMS LIABILITY FOR DAMAGES RESULTING FROM THE USE OF THIS DOCUMENT OR THE INFORMATION OR WORKS PROVIDED HEREUNDER. 

Statement of Purpose

The laws of most jurisdictions throughout the world automatically confer exclusive Copyright and Related Rights (defined below) upon the creator and subsequent owner(s) (each and all, an "owner") of an original work of authorship and/or a database (each, a "Work").

Certain owners wish to permanently relinquish those rights to a Work for the purpose of contributing to a commons of creative, cultural and scientific works ("Commons") that the public can reliably and without fear of later claims of infringement build upon, modify, incorporate in other works, reuse and redistribute as freely as possible in any form whatsoever and for any purposes, including without limitation commercial purposes. These owners may contribute to the Commons to promote the ideal of a free culture and the further production of creative, cultural and scientific works, or to gain reputation or greater distribution for their Work in part through the use and efforts of others.

For these and/or other purposes and motivations, and without any expectation of additional consideration or compensation, the person associating CC0 with a Work (the "Affirmer"), to the extent that he or she is an owner of Copyright and Related Rights in the Work, voluntarily elects to apply CC0 to the Work and publicly distribute the Work under its terms, with knowledge of his or her Copyright and Related Rights in the Work and the meaning and intended legal effect of CC0 on those rights.

1. Copyright and Related Rights. A Work made available under CC0 may be protected by copyright and related or neighboring rights ("Copyright and Related Rights"). Copyright and Related Rights include, but are not limited to, the following:

    the right to reproduce, adapt, distribute, perform, display, communicate, and translate a Work;
    moral rights retained by the original author(s) and/or performer(s);
    publicity and privacy rights pertaining to a person's image or likeness depicted in a Work;
    rights protecting against unfair competition in regards to a Work, subject to the limitations in paragraph 4(a), below;
    rights protecting the extraction, dissemination, use and reuse of data in a Work;
    database rights (such as those arising under Directive 96/9/EC of the European Parliament and of the Council of 11 March 1996 on the legal protection of databases, and under any national implementation thereof, including any amended or successor version of such directive); and
    other similar, equivalent or corresponding rights throughout the world based on applicable law or treaty, and any national implementations thereof.

2. Waiver. To the greatest extent permitted by, but not in contravention of, applicable law, Affirmer hereby overtly, fully, permanently, irrevocably and unconditionally waives, abandons, and surrenders all of Affirmer's Copyright and Related Rights and associated claims and causes of action, whether now known or unknown (including existing as well as future claims and causes of action), in the Work (i) in all territories worldwide, (ii) for the maximum duration provided by applicable law or treaty (including future time extensions), (iii) in any current or future medium and for any number of copies, and (iv) for any purpose whatsoever, including without limitation commercial, advertising or promotional purposes (the "Waiver"). Affirmer makes the Waiver for the benefit of each member of the public at large and to the detriment of Affirmer's heirs and successors, fully intending that such Waiver shall not be subject to revocation, rescission, cancellation, termination, or any other legal or equitable action to disrupt the quiet enjoyment of the Work by the public as contemplated by Affirmer's express Statement of Purpose.

3. Public License Fallback. Should any part of the Waiver for any reason be judged legally invalid or ineffective under applicable law, then the Waiver shall be preserved to the maximum extent permitted taking into account Affirmer's express Statement of Purpose. In addition, to the extent the Waiver is so judged Affirmer hereby grants to each affected person a royalty-free, non transferable, non sublicensable, non exclusive, irrevocable and unconditional license to exercise Affirmer's Copyright and Related Rights in the Work (i) in all territories worldwide, (ii) for the maximum duration provided by applicable law or treaty (including future time extensions), (iii) in any current or future medium and for any number of copies, and (iv) for any purpose whatsoever, including without limitation commercial, advertising or promotional purposes (the "License"). The License shall be deemed effective as of the date CC0 was applied by Affirmer to the Work. Should any part of the License for any reason be judged legally invalid or ineffective under applicable law, such partial invalidity or ineffectiveness shall not invalidate the remainder of the License, and in such case Affirmer hereby affirms that he or she will not (i) exercise any of his or her remaining Copyright and Related Rights in the Work or (ii) assert any associated claims and causes of action with respect to the Work, in either case contrary to Affirmer's express Statement of Purpose.

4. Limitations and Disclaimers.

    No trademark or patent rights held by Affirmer are waived, abandoned, surrendered, licensed or otherwise affected by this document.
    Affirmer offers the Work as-is and makes no representations or warranties of any kind concerning the Work, express, implied, statutory or otherwise, including without limitation warranties of title, merchantability, fitness for a particular purpose, non infringement, or the absence of latent or other defects, accuracy, or the present or absence of errors, whether or not discoverable, all to the greatest extent permissible under applicable law.
    Affirmer disclaims responsibility for clearing rights of other persons that may apply to the Work or any use thereof, including without limitation any person's Copyright and Related Rights in the Work. Further, Affirmer disclaims responsibility for obtaining any necessary consents, permissions or other rights required for any use of the Work.
    Affirmer understands and acknowledges that Creative Commons is not a party to this document and has no duty or obligation with respect to this CC0 or use of the Work.

**Comment by nyalldawson** [comment]
Sounds good to me Tim!

**Comment by timlinux** [comment]
Check the updates for the deployed work @nyalldawson - thanks for your suggestion!

**Comment by nyalldawson** [comment]
Thanks @sumandari @timlinux !

I think there's one missing part here -- we should explicitly state the license also on the style details page, not just the upload page. I.e. https://plugins.qgis.org/styles/3/ should say state somewhere that the item is cc-0, with a link to https://creativecommons.org/publicdomain/zero/1.0/ and the corresponding cc icon

**Comment by timlinux** [comment]
Thanks @nyalldawson 


@sumandari is adding it in #146
