### ISSUE TITLE
Add small icon in front of marker? (styles sharing)

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Django#149]
Hi, tiny detail.

But it would be nice to add a small icon in front of 'Marker' in the left menu:

![Screenshot-20210115132223-304x446](https://user-images.githubusercontent.com/731673/104727055-fd07e100-5734-11eb-8646-ee0ba9e61144.png)

It would just look a little nicer :-)

Another minor thing: I do miss the url to this repo, so people can easily see where the code is (and maybe issue features/bugs)? Only OpenIt and Kartoza links in the footer (while I think there was a github link earlier?). Or is this by purpose/choice?

**Comment by sumandari** [comment]
Hi @rduivenvoorde, thank you for the input. Do you have any suggestion what the best icon image shall be added into it? @timlinux would you please advise on this.

About the github link, can we added it in the footer? e.g:
![image](https://user-images.githubusercontent.com/40058076/105328035-938f4300-5c0a-11eb-91be-cc2b667509fd.png)

And shall we update the license information mentioned on style/projects/model page? Since they are using CC-0 instead of CC BY-SA?

**Comment by rduivenvoorde** [comment]
@sumandari about the icon, I would take one of the standard (familiar looking one):

![Screenshot-20210121102411-379x341](https://user-images.githubusercontent.com/731673/105330735-ed741680-5bd2-11eb-8dd8-139174865e18.png)

I would take a small red dot I think...

About available on Github: I see that the little octocat-icon of github goes to github.com/qgis it could go to https://github.com/qgis/QGIS-Django ? Or indeed the little sentence you added, maybe text: "Source availabe on Github"?

**Comment by sumandari** [comment]
Thanks @rduivenvoorde. Now you can see the small red dot as marker icon on the web page. :-)
![image](https://user-images.githubusercontent.com/40058076/105333656-f1268e00-5c10-11eb-94f0-370c50405c49.png)

About the github repo information, in my opinion, I prefer to change the link on octocat-icon to https://github.com/qgis/QGIS-Django as you mentioned (if it's fine to replace the link). For me myself it looks more obvious rather than read the text.

**Comment by timlinux** [comment]
Thanks @sumandari and @rduivenvoorde
