### ISSUE TITLE
Plugin details mixup 'created_by' 'owner' 'author' and 'maintainer'

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Django#303]
I'm being contacted by (old) plugin owners who still see there name in plugins.qgis.org while the plugin details in metadata.txt OR in the admin pages are all updated.
As an example: 

![image](https://github.com/qgis/QGIS-Django/assets/731673/bb04b762-9f49-4040-b907-4efd790f44c5)

This 'arichard' is not in the metadata or edit page anymore

![image](https://github.com/qgis/QGIS-Django/assets/731673/c0e022ba-cd33-4e4b-90f4-f27b624c0446)

Looking into the code

https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/templates/plugins/plugin_detail.html#L131

It looks like we take the list of (mail addresses?) in created_by and then the the first one alphabetically?
Which in this case is apparently the wrong one.

Would a solution be:
- either rename 'Maintainer' to 'Created by' in the plugin details page and then show the list of ALL users who created versions of the plugin. In that way if an organisation really want't to get rid of a name, they can remove a version (with the 'created_by')
- OR order the versions by version number an just take the newest version of a plugin and from THAT one take the created_by user?

**Comment by gacarrillor** [comment]
> It looks like we take the list of (mail addresses?) in created_by and then the the first one alphabetically?

As of now, I guess the `maintainer` is the person who first submitted the plugin.

**Comment by Xpirix** [comment]
> - either rename 'Maintainer' to 'Created by' in the plugin details page and then show the list of ALL users who created versions of the plugin. In that way if an organisation really want't to get rid of a name, they can remove a version (with the 'created_by')

> - OR order the versions by version number an just take the newest version of a plugin and from THAT one take the created_by user?

We could also combine these proposed solutions by keeping both fields so `Created by` would be the person who first submitted the plugin and `Maintainer` would be the user who created the newest version like the following screenshot:

![image](https://github.com/qgis/QGIS-Django/assets/43842786/22b72445-b569-49ef-a583-7bb53ff80eca)

**Comment by gacarrillor** [comment]
@Xpirix, what about showing a Maintainer field in the edit form with the Plugin creator selected by default and the plugin owners as options.

By default:
![image](https://github.com/qgis/QGIS-Django/assets/652785/cb7880b8-c0fb-43b1-ab29-f4021dfaad61)

Options:
![image](https://github.com/qgis/QGIS-Django/assets/652785/1ad9d8a4-8dc0-4d6d-b9ce-fa7d63628c49)

**Comment by Xpirix** [comment]
Hello @gacarrillor , that's a good idea, thank you. I will implement this. 

I also take advantage of the current issue to replace all Owner appearances with Collaborators, to be consistent with:
https://github.com/qgis/QGIS-Django/pull/254 as discussed with @dimasciput 

Best regards.

**Comment by Xpirix** [comment]
Dear @gacarrillor,

Since the field Maintainer refers to the original field `created_by`, the selected Owner becomes the Plugin creator after an update. Then, the old plugin creator won't be part of the plugin anymore because this user is already excluded when the form is initiated or saved according to the following codes:
https://github.com/qgis/QGIS-Django/blob/08f01b4f62a2a75f05947ebf7f39d46c60ff249b/qgis-app/plugins/views.py#L555-L557
https://github.com/qgis/QGIS-Django/blob/08f01b4f62a2a75f05947ebf7f39d46c60ff249b/qgis-app/plugins/views.py#L575-L578

Please find below a GIF:
![Maintainer_field](https://github.com/qgis/QGIS-Django/assets/43842786/29ddd9f6-74a9-4482-a2f4-c8046d92f638)

Is this OK or should we include the plugin creator as part of the owners/collaborators? I'm sorry but I'm a bit lost here.

Thank you,
Best regards.

**Comment by gacarrillor** [comment]
Hi @Xpirix, thanks for your work!

Sorry for the delay, I guess right now we're almost at opposite sides (antipodes) in the :earth_asia: 

It looks great, I think it's getting closer.

> Since the field Maintainer refers to the original field created_by, the selected Owner becomes the Plugin creator after an update.

In my opinion, it'd be good to preserve the original `created_by` user internally (i.e., not necessarily for display purposes), even if it's not the maintainer anymore.

To display the `created_by` field in the plugin details could be optional (e.g., via a checkbox in the plugin edit page) and it could be `False` by default (since the `Maintainer` field will have the `created_by` user selected by default anyways).

However, once a plugin admin selects an owner/collaborator as the new maintainer, he/she could click the checkbox to show the `created_by` user in the plugin details, and thus acknowledge or credit him/her for his/her original work.

![image](https://github.com/qgis/QGIS-Django/assets/652785/ac7876ae-9e29-4e3b-b2bd-bfb1f367b6ae)

In this way, the `created_by` user will always be an option in the `Maintainers` combobox.


Does that make sense?

**Comment by Xpirix** [comment]
Hello @gacarrillor , my pleasure. 

Yes, that makes sense. I also think that it's better to preserve the original `created_by` field. So I will create 2 new fields in the model:
- a field `maintainer` to store the maintainer user. It takes the value from `created_by` by default. This new field will be displayed as the maintainer in the plugin details.
- a field `display_created_by` to display the `created_by` in the plugin details. This is set to False by default.

**Comment by gacarrillor** [comment]
Solved in https://github.com/qgis/QGIS-Django/pull/316
@dimasciput @Xpirix, please close this issue.
